/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DataRegistry__factory } from "./DataRegistry__factory";
export { Identity__factory } from "./Identity__factory";
export { ScoreSBT__factory } from "./ScoreSBT__factory";
