/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DataRegistry } from "./DataRegistry";
export type { Identity } from "./Identity";
export type { ScoreSBT } from "./ScoreSBT";
